### PR TITLE
Functional cypher

### PR DESCRIPTION
**Pull request by SolanaO**
Add functional cypher utilities and sample finetuning notebooks.

### CODE REVIEW

**Comment by tomasonjo** [comment]
Hi Silvia,

thanks for your submission.
I'm trying to figure out what's the best way to put all the code in the repository...
It would make sense to put the dataset generation under the dataset folder.
As for finetuning, do you think is it fine if they are separate under /finetuning folder, or should be kept together? We can always duplicate the finetuning notebooks as well if that would be needed.

**Comment by SolanaO** [comment]
Hi Tomaz,

I was thinking the same when I created the branch. I agree with you, this way the repo will have consistency: dataset generation to dataset folder and finetuning notebooks to finetuning. The finetuning notebooks can be separate, as they do not depend on the data generation code. The sample dataset I included is based on the KG described here : "https://github.com/SolanaO/Knowledge_Graphs_Assortment/tree/master/arXiv_KG".

**Comment by tomasonjo** [comment]
Ok great, let's split then into /dataset/functional_cypher and /finetuning/huggingface something... IDK if you can come up with a good name for finetuning folder :) And please attribute yourself everywhere, because attribution is important!

**Comment by SolanaO** [comment]
I moved all data generation to datasets/functional_cypher and added a link to my blog in readme. Also created a new folder huggingface in finetuning. I added my name by the notebook titles. Thanks for the suggestion!

**Review by tomasonjo — APPROVED** [review]

**Pull request merged**
